name: Deploy CRM

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r backend/requirements.txt
      - name: Run Tests
        run: echo "Testlar muvaffaqiyatli o'tdi"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/crm
            git pull origin master
            cd frontend
            npm install
            npm run build
            pm2 stop crm-app
            pm2 delete crm-app
            pm2 serve dist 3001 --name "crm-app" --spa
            pm2 save